### ISSUE TITLE
TODO list for airspeed fusion

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/ecl#77]
- [x] Increase the airspeed readout rate to 14 Hz and 
- [x] And test in SITL
- [x] Make the estimator publish to the wind topic PX4/Firmware#4147
- [ ] Optimize the calculation of the covariance matrix by taking advantage of the sparseness in H
- [x] Add protection against the denominator in line 76 being too small #86
- [x] Move the check for if we want to fuse airspeed somewhere higher up
- [x] Implement the logic of when to fuse airspeed, i.e. not on the ground etc.
- [x] Make sure the wind states and covariances are initialized correctly when we start fusing airspeed
- [x] Clean up the use of TAS/EAS
- [x] Fix the issue with landed detected PX4/Firmware#4155
- [x] Rename _airspeed_sample_delayed.airspeed to _airspeed_sample_delayed.true_airspeed

**Comment by LorenzMeier** [comment]
@CarlOlsson Where are we standing with this?

**Comment by CarlOlsson** [comment]
I think all of the remainging points except the calculation of the covariance matrix were resolved by @tumbili ?

**Comment by tumbili** [comment]
@CarlOlsson Yes, we can close this. Everything is in now, we just have to go on with testing.
